% figure window for interactively selecting stuff

function FigA2

% Define initial stuff

% Figure and axes

MainFigh=figure;
set(gcf,'units','normalized','Position', [ 0.1 0.15 0.5722 0.622 ]);
Colours={'b-';'r:';'g--';'k-.';'m-';'c:';'y--'};
axish=axes('position',[ 0.05 0.05 0.75 0.8 ], ...
   'Userdata',Colours,'nextplot', 'add');  % Userdata holds linestyles

% axis re-size controls

% Xmin
edX1h=uicontrol('style','edit', 'Units','points',...
   'position', [ 15.75 341.25 25 13 ], ...
   'Tag', 'edX1', ...
   'callback', 'FigAcode2 Set', ...
   'String','');
txtX1h=uicontrol('style','text', 'Units','points',...
   'String','X1', ...
   'position', [ 3 341 13.5 12 ]);

%Xmax
edX2h=uicontrol('style','edit', 'Units','points',...
   'position', [ 15.75 326.25 25 13 ], ...
   'Tag', 'edX2', ...
   'callback', 'FigAcode2 Set', ...
   'String','');
txtX2h=uicontrol('style','text', 'Units','points',...
   'String','X2', ...
   'position', [ 3 327 14 12 ]);

%Ymin
edY1h=uicontrol('style','edit', 'Units','points',...
   'position',[ 58 341 25 13 ] , ...
   'Tag', 'edY1', ...
   'callback', 'FigAcode2 Set', ...
   'String','');
txtY1h=uicontrol('style','text', 'Units','points',...   
   'String','Y1', ...
	'position',[ 44 341 13.5 12 ] );

%Ymax
edY2h=uicontrol('style','edit', 'Units','points',...
   'position', [ 58 326.25 25 13 ], ...
   'Tag', 'edY2', ...
   'callback', 'FigAcode2 Set', ...
   'String','');
txtY2h=uicontrol('style','text', 'Units','points',...
   'String','Y2', ...
   'position',[ 42.75 327 13.5 12 ] );

% Buttons: grid, set and reset

chGridh=uicontrol('style','checkbox', 'Units','points',...
   'position', [ 2 310.5 30 13 ], ...
   'Tag', 'chGrid', ...
   'callback', 'FigAcode2 GridOn', ...
   'Value', 0, ...
   'String','Grid');

butSeth=uicontrol('style','pushbutton', 'Units','points',...
   'position', [ 35 310.5 18.75 13 ], ...
   'Tag', 'butSet', ...
   'callback', 'FigAcode2 Set', ...
   'String','Set');

butReseth=uicontrol('style','pushbutton', 'Units','points',...
   'position', [ 58 310.5 25 13 ], ...
   'Tag', 'butReset', ...
   'Userdata', [0 1 0 1], ...
   'callback', 'FigAcode2 Reset', ...
   'String','Reset');

% List and delete button for current lines 
listLinesh=uicontrol('style','listbox','Units','normalized', ...
   'position', [ 0.58 0.85 0.22 0.15 ], ...
   'Tag', 'listLines', ...
   'callback', 'FigAcode2 ListDirec', ...
   'String',{''}, ...
   'Userdata',[]); % Userdata holds the line handles

edClearh=uicontrol('style','pushbutton', 'Units','normalized', ...
   'position', [ 0.52 0.895 0.05 0.035 ], ...
   'Tag', 'edClear', ...
   'callback', 'FigAcode2 ClearLine', ...
   'String','Clear');

% menus and boxes to display possibilities for plotting/deleting

edDelh=uicontrol('style','pushbutton', 'Units','normalized',...
   'position', [ 0.52 0.965 0.05 0.035 ], ...
   'Tag', 'edDel' , ...
   'callback', 'FigAcode2 DelFile', ...
   'String','Del');

% stuff for x

% File
popXfileh=uicontrol('style','popupmenu','Units','normalized', ...
   'position', [ 0.2 0.6 0.15 0.4 ], ...
   'Tag', 'popXfile', ...
   'callback', 'FigAcode2 ListXVar', ...
   'String',{''});

% Variables from File 
popXvarh=uicontrol('style','popupmenu','Units','normalized', ...
   'position', [ 0.215 0.55 0.135 0.4 ], ...
   'Tag', 'popXvar', ...
   'callback', '', ...
   'String',{'none'}, ...
   'Userdata', {''});
txtXh=uicontrol('style','text', 'Units','normalized',...
   'String','X', ...
   'position',[ 0.195 0.915 0.015 0.03 ] );

% Path to File
edXdirh=uicontrol('style','edit', 'Units','normalized',...
   'position', [ 0.2 0.86 0.15 0.04 ], ...
   'Tag', 'edXdir', ...
   'callback', '', ...
   'String','');

% stuff for y
% File
popYfileh=uicontrol('style','popupmenu','Units','normalized', ...
   'position', [ 0.36 0.6 0.15 0.4 ], ...
   'Tag', 'popYfile', ...
   'callback', 'FigAcode2 ListYVar', ...
   'String',{''});
% Variables from File 
popYvarh=uicontrol('style','popupmenu','Units','normalized', ...
   'position', [ 0.375 0.55 0.135 0.4 ], ...
   'Tag', 'popYvar', ...
   'callback', '', ...
   'String',{''});
txtYh=uicontrol('style','text', 'Units','normalized',...
   'String','Y', ...
   'position',[ 0.355 0.915 0.015 0.03 ] );

% Path to File
edYdirh=uicontrol('style','edit', 'Units','normalized',...
   'position', [ 0.36 0.86 0.15 0.04 ], ...
   'Tag', 'edYdir', ...
   'callback', '', ...
   'String','');

% Browser
% Current files
listFilesh=uicontrol('style','listbox','Units','normalized', ...
   'position', [ 0.8 0.55 0.2 0.2 ], ...
   'Tag', 'listFiles', ...
   'callback', 'FigAcode2 Browse', ...
   'String',{''});

% File
edFileh=uicontrol('style','edit', 'Units','normalized',...
   'position', [ 0.85 0.75 0.15 0.035 ], ...
   'Tag', 'edFile', ...
   'callback', 'FigAcode2 ListMat', ...
   'String','');
txtFileh=uicontrol('style','text', 'Units','normalized',...
   'String','File', ...
   'position',[ 0.8 0.75 0.04 .035 ] );

% Directory
direc=[pwd]; 	%get current directory and put a slash if needed
N=length(direc);
if ((direc(N)~='\')&(direc(N)~='/'))
   direc=[pwd '\'];
end
edDirh=uicontrol('style','edit', 'Units','normalized',...
   'position', [ 0.8 0.8 0.2 0.035 ], ...
   'Tag', 'edDir', ...
   'callback', 'FigAcode2 ListMat', ...
   'String',direc);

FigAcode2 ListMat; % List current files

% Load button
butLoadh=uicontrol('style','pushbutton','Units','normalized', ...
   'position', [ 0.875 0.5 0.05 0.035 ], ...
   'Tag', 'butLoad', ...
   'callback', 'FigAcode2 LoadA', ...
   'String','Load');

% Plot button
butPloth=uicontrol('style','pushbutton','Units','normalized', ...
   'position', [ 0.52 0.93 0.05 0.035 ], ...
   'Tag', 'butPlot', ...
   'callback', 'FigAcode2 PlotA', ...
   'Userdata', 0, ... 		% Userdata holds # of lines
   'String','Plot');

%Clear All button
butClAllh=uicontrol('style','pushbutton','Units','normalized', ...
   'position', [ 0.52 0.86 0.05 0.035 ], ...
   'Tag', 'butClAll', ...
   'callback', 'FigAcode2 ClearAll', ...
   'Userdata', 0, ... 		% Userdata could hold saved data 
   'String','ClAll');
