% ica gui

close all;
clear;


% *******************************
% ********** figures ********
% *******************************

RawImages = figure('Units','points',...
   'Name','Raw Images',...
   'Position',[5 236 326 312],...
   'Tag','RawImages');

FilteredImages = figure('Units','points',...
   'Name','Filtered Images',...
   'Position',[5 236 326 312],...
   'Tag','FilteredImages');

ICImages = figure('Units','points',...
   'Name','Independent Components',...
   'Position',[5 236 326 312],...
   'Tag','ICImages');

MainGui = figure('Units','points', ...
   'Position',[336 236 417 312], ...
   'Tag','MainFig');

% **********************************
% ********* MainGui Children *******
% **********************************

% **********************************
% ********** push buttons **********
% **********************************

LoadImagesButton = uicontrol('Parent',MainGui, ...
   'Units','points', ...
   'Callback','ICA1Calls loadim;', ...
	'Position',[8 280 60 25], ...
	'String','Refresh Image Set', ...
	'Tag','LoadImageButton');

DisplayImages = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls DisplayRawImages', ...
	'ListboxTop',0, ...
	'Position',[8 250 60 25], ...
	'String','Display Images', ...
	'Tag','DisplayRawImageBut');

FilterButton = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls Filter;', ...
	'ListboxTop',0, ...
	'Position',[8 220 60 25], ...
	'String','filter', ...
	'Tag','FilterButton');

MainCalcButton = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls maincalc;', ...
	'ListboxTop',0, ...
	'Position',[8 190 60 25], ...
	'String','Go', ...
	'Tag','GoButton');

ThresholdButton = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls Threshold;', ...
	'ListboxTop',0, ...
	'Position',[8 160 60 25], ...
	'String','Threshold IC', ...
	'Tag','ThreshButton');


% *******************************
% ********** List boxes *********
% *******************************

ListBox1=uicontrol('parent',MainGui,...
   'style','listbox',...
   'Units','points', ...
   'position',[70 252 130 54],...
   'tag','FileNameList');



% ***********************************
% *********** pop up menus **********
% ***********************************


DisplayPanelMenu = uicontrol('Parent',MainGui, ...
   'Units','points', ...
   'Callback','ICA1Calls CaptureDisplay;', ...
	'Position',[342 262 50 12], ...
   'Style','popupmenu', ...
   'string',{0},...
   'Tag','DisplayPanel');

cellarray={'CroppedImHistArray'
    'RawImSkewArray'
    'RawImKurtosisArray'
    'EigenImHistArray'
    'EigenImSkewArray'
    'EigenImKurtosisArray'
    'ICImHistArray'
    'ICImSkewArray'
    'ICImKurtosisArray'};

DisplayDataArrayMenu = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls DisplayDataArray;', ...
	'ListboxTop',0, ...
	'Position',[300 280 91 12], ...
	'String',cellarray, ...
	'Style','popupmenu', ...
	'Tag','DisplayDataArray', ...
	'Value',1);

cellarray={'RawImages'
    'FilteredImages'
    'ICImages'};


DisplayImageArrayMenu = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls ShowFigure;', ...
	'ListboxTop',0, ...
	'Position',[212 279 86 12], ...
	'String',cellarray, ...
	'Style','popupmenu', ...
	'Tag','DisplayFigure', ...
	'Value',1);

cellarray={'surf'
    'contour'
    'surfc'
    'imagesc'};

GraphTypeMenu = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'Callback','ICA1Calls CaptureDisplay;', ...
	'ListboxTop',0, ...
	'Position',[258 262 80 12], ...
	'String',cellarray, ...
	'Style','popupmenu', ...
	'Tag','GraphType', ...
	'Value',4);


% ************************************
% *************  axes ****************
% ************************************

mainaxes = axes('Parent',MainGui, ...
	'Position',[0.45 0.07 0.5 0.6], ...
   'Tag','mainaxes',...
   'visible','off');

% ************************************
% ********* static text strings ******
% ************************************

Stext1 = uicontrol('Parent',MainGui, ...
   'units','points',...
    'BackgroundColor',[0.25 0.50 0.50], ...
	'ForegroundColor',[0 1 0], ...
	'ListboxTop',0, ...
	'Position',[15 87 90 12], ...
	'String','specifications', ...
	'Style','text', ...
	'Tag','StaticText1');

Stext2 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[71 238 41 12], ...
	'String','filter size', ...
	'Style','text', ...
	'Tag','StaticText2');

Stext3 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[71 224 41 12], ...
	'String','comp ratio', ...
	'Style','text', ...
	'Tag','StaticText3');

SText4 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[15 16 49 12], ...
	'String','number  ICs', ...
	'Style','text', ...
	'Tag','StaticText4');

SText5 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.25 0.5 0.5], ...
	'ForegroundColor',[0 1 0], ...
	'ListboxTop',0, ...
	'Position',[212 292 85 12], ...
	'String','Current Image Window', ...
	'Style','text', ...
	'Tag','StaticText5');

SText6 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.25 0.5 0.5], ...
	'ForegroundColor',[0 1 0], ...
	'ListboxTop',0, ...
	'Position',[298 292 93 12], ...
	'String','Current Data Window', ...
	'Style','text', ...
   'Tag','StaticText6');

SText7 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[15 30 49 12], ...
	'String','last Evect', ...
	'Style','text', ...
	'Tag','StaticText7');

SText8 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[15 44 49 12], ...
	'String','first Evect', ...
	'Style','text', ...
	'Tag','StaticText8');


% ************************************
% ********** editable text ***********
% ************************************

Etext1 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[114 238 24 12], ...
	'String','0', ...
	'Style','edit', ...
   'Tag','EditText1');

EText2 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[114 224 24 12], ...
	'String','1', ...
	'Style','edit', ...
   'Tag','EditText2');


EText3 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[65 44 40 12], ...
	'String','1', ...
	'Style','edit', ...
   'Tag','EditText3');

EText4 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[65 31 41 12], ...
	'String','10', ...
	'Style','edit', ...
   'Tag','EditText4');

EText5 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[65 16 41 12], ...
	'String','4', ...
	'Style','edit', ...
	'Tag','EditText5');

% ***********************************
% *********** check boxes ***********
% ***********************************

Checkbox1 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[15 73 90 12], ...
	'String','disable stats', ...
	'Style','checkbox', ...
	'Tag','Checkbox1', ...
   'Value',1);

Checkbox2 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'ListboxTop',0, ...
	'Position',[15 58 90 12], ...
	'String','disable sep PCA', ...
	'Style','checkbox', ...
	'Tag','Checkbox2', ...
   'Value',1);


Checkbox3 = uicontrol('Parent',MainGui, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.75 0.75], ...
	'Callback','ICA1Calls CaptureDisplay', ...
	'ListboxTop',0, ...
	'Position',[211 260 45 12], ...
	'String','invert', ...
	'Style','checkbox', ...
	'Tag','Checkbox3', ...
	'Value',1);


% ************************************
% ****** Thresholded IC Figure *******
% ************************************
