function irr2u(Anzahl, Weite, Driftx, Drifty)

% IRR2U(ANZAHL,WEITE,DRIFTX,DRIFTY) simulates an two-dimensional
% asymmetric random walk and plots it.
% Anzahl is the number of steps, weite is the maximum step size.
% Driftx and drifty can cause a drift of the particle to the right
% and the top respectively.
%
% IRR2S(ANZAHL,WEITE) uses driftx = drifty = 0.
%
% IRR2S uses anzahl = 1000, weite = 10 in addition.

% This file was generated by students as a partial fulfillment 
% for the requirements of the course "Fractals", Winter term
% 2004/2005, Stuttgart University.	

% Author : Fabian Hansch, Stefanie Schetter
% Date   : Dec 2004
% Version: 1.0


% default setting
if (nargin < 4)
    Driftx = 0;
    Drifty = 0;
end
if (nargin < 2)
    Anzahl = 1000;
    Weite = 10;
end

clf;
axis  square; axis equal;
% hold on;
Position = zeros(2, Anzahl+1);
Position(1, 1) = 0; Position(2, 1) = 0;

% measure the elapsed time
tic;
for x = 1:Anzahl
    % random value out of [0, 2pi] for the angle
    ZufallWinkel = 2*pi*rand(1);
    % random step length out of [0, weite]
    ZufallWeite = Weite*rand(1);
    Position(1, x+1) = round(Position(1, x)+ZufallWeite*cos(ZufallWinkel))+Driftx;
    Position(2, x+1) = round(Position(2, x)+ZufallWeite*sin(ZufallWinkel))+Drifty;
    plot(Position(1,1:x), Position(2,1:x), 'b-');
    m=max(20,max(max(abs(Position))));
    axis([-m m -m m])
end;
toc;
x = 1:Anzahl+1; y = 1:Anzahl+1;
% plotting the random walk
plot(Position(1,x), Position(2,y), 'b-');
hold off;