function [X,dfdX,dfdU]=Movement_Model(X,U,dt)

% new estimated position
X=X+[X(3);X(4);U(1);U(2)]*dt;

% jacobian calculations
dfdX=[1,0,dt,0;...
            0,1,0,dt;...
            0,0,1,0;...
            0,0,0,1];
dfdU=[0,0;...
            0,0;...
            dt,0;...
            0,dt];
